apiVersion: v1
kind: Service
metadata:
  name: azurite-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: azurite-k8s
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001
      nodePort: 30001